# see https://docs.silverstripe.org/en/developer_guides/configuration/configuration/
---
Name: coresearchfilters_fuzzy
---
SilverStripe\Core\Injector\Injector:
  DataListFilter.FuzzyPartialMatch:
    class: Sunnysideup\FuzzyPartialMatchFilter\FuzzyPartialMatchFilter
---
Name: coresearchaliases_fuzzy
---
SilverStripe\Core\Injector\Injector:
  FuzzyFilter: '%$DataListFilter.FuzzyPartialMatch'
