# see https://docs.silverstripe.org/en/developer_guides/configuration/configuration/
---
Name: coresearchfilters_fuzzy
---
SilverStripe\Core\Injector\Injector:
  DataListFilter.Fuzzy:
    class: Sunnysideup\FuzzyPartialMatchFilter\FuzzyPartialMatchFilter
